### PR TITLE
Always copy code and output when changing new language

### LINKED ISSUE #11: Changing the language changes code input to "Hello world!" each time
Ideally, I think if you have already inputted code into the textbox and then change the language, the code input should keep whatever was already in there. For example, consider if someone inputs code but forgets to change the language later. 

We should discuss later if this is behavior we want.

### PR DESCRIPTION
**Pull request by narrator0**
This attempts to resolve #11. I change to plugin to always copy the previous code and output to the new Thebelab instance. I think the sample code is not important at all. We should move whatever code and output to the new instance. @celine168 let me know what you think.

### CODE REVIEW

**Review by celine168 — COMMENTED** [review]
I think this works. Another possibility I was thinking was to keep the sample code if they haven't edited the code input box yet, and if they already have, then keep the code inside. I'm not sure which option is better. What's your opinion?

**Comment by narrator0** [comment]
I also thought about that option. But this will require we have somewhere to store whether the code is dirty or not. In which we are only passing in a config dictionary to create the dialog. I'm not sure where can could store this information? And since I think this approach is also valid, I chose the easier approach.

**Comment by narrator0** [comment]
@celine168 I think we can merge this. The sample code is not necessary since the author is going to delete it and remove it anyway. I think keep the code is the best solution.

**Comment by narrator0** [comment]
I looked at the implementation myself. I think we should still keep the sample code since we made the starting language dynamic in #24. As there are a lot of commits to master after this PR that make this branch now have conflicts with master. I suggest rewrite the code and reopen another PR.

**Pull request closed without merging**
