### PR TITLE
Remove trailing colon per issue #65

### LINKED ISSUE #65: Remove trailing colon from labels
In plugin.scss, please add a line of CSS to counteract this CSS:
```CSS
.mt-label:after, label:after {
    content: ':';
}
```

image

### PR DESCRIPTION
**Pull request by celine168**
Resolves #65, per @Miniland1333's request (thank you!)

### CODE REVIEW

**Review by narrator0 — CHANGES_REQUESTED** [review]
The `content` attribute add pure text after the element. In this case adds a colon. This is kind of a global thing on MindTouch. I don't think simply changing it to something like `content: '';` will be a good fix since this will change other plugins as well.

It might be better if we scope this under something like `.mt-editor-dialog-binderDialog` so that only our plugin on MindTouch get changed.

**Comment by celine168** [comment]
Do you mean something like this:
```
.mt-editor-dialog-binderDialog.mt-label:after, .mt-editor-dialog-binderDialog.label:after {
  content: '';
}
```

**Comment by Miniland1333** [comment]
> Do you mean something like this:
> 
> ```
> .mt-editor-dialog-binderDialog.mt-label:after, .mt-editor-dialog-binderDialog.label:after {
>   content: '';
> }
> ```

Based on testing this, this does seem to be scoped correctly now. I'm glad you are injecting the `mt-editor-dialog-binderDialog` class

**Comment by narrator0** [comment]
`.mt-editor-dialog-binderDialog.mt-label:after` means an element that has both classes. But I mean `.mt-editor-dialog-binderDialog .mt-label:after` which is `.mt-label` that is a children of `.mt-editor-dialog-binderDialog`.

> https://www.w3schools.com/cssref/css_selectors.asp

**Comment by celine168** [comment]
I see, got it. Thank you!

**Review by narrator0 — APPROVED** [review]
Removed extra dot in front of label. Tested on production and it works.

**Pull request merged**
