### PR TITLE
C++ release

### PR DESCRIPTION
**Pull request by celine168**
This release includes:
* Addition of the C++ kernel
* Documentation for using the editor on the site
* Updates the Julia version to request from Binder
* Fixes bug converting from code in the editor to code in the dialog
* Security updates

### CODE REVIEW

**Comment by moorepants** [comment]
I don't see anything here that would cause trouble on production. I think we should merge.

**Review by narrator0 — APPROVED** [review]
Should this be `1.0.2` or `1.1.0`? Since we added additional support for c++, maybe `1.1.0` is better?

**Comment by celine168** [comment]
`1.1.0` sounds good to me.

**Comment by moorepants** [comment]
I think following this https://semver.org/ for version numbers is generally a good idea.

**Pull request merged**
