### PR TITLE
Fix/add status field when loading thebe

### LINKED ISSUE #128: Hide indicator HTML in editor view
The indicator will show on the editor view, it may be confusing for authors. We should add in editor only css to hide this.

### PR DESCRIPTION
**Pull request by narrator0**
Somehow also resolves #128.

Change how we insert Thebe status fields. Now anytime we try to load thebe script, we'll try to insert the status field on that page. This way, any existing page will also have the status field.

### CODE REVIEW

**Comment by celine168** [comment]
I can review it in an hour-ish, but if someone else wants to take a crack at it, please go ahead.

**Review by celine168 — APPROVED** [review]
I apologize because I completely forgot to review this yesterday.
It all looks good to me! I don't think there's a way to test this on existing pages until we deploy, so I think we will just have to see.

**Comment by narrator0** [comment]
@celine168 you can go to old pages on query and see if it shows. It's deployed on query now.

**Comment by celine168** [comment]
Yes still looks good!

**Pull request merged**
