### PR TITLE
env.yml and postBuild

### PR DESCRIPTION
**Pull request by tannavee**

### CODE REVIEW

**Comment by narrator0** [comment]
We need to leave the yaml file and postbuild on the branch. Don't need to merge into master since we are accessing it using `ref`. We should only merge the second commit.

@tannavee can you open a new branch that only contain the second commit and resbmit a PR?

also add requirejs in it since this is a replace of #29.

**Comment by tannavee** [comment]
@narrator0  to summarize:

Python-Env: will contain the env.yaml and postBuild
Master: have directions to the python-env branch

**Comment by narrator0** [comment]
Correct

**Comment by narrator0** [comment]
Closing because we have #34.

**Pull request closed without merging**
