### PR TITLE
Switch from checkboxes to radio buttons

### LINKED ISSUE #20: Should not allow both checkboxes checked

### PR DESCRIPTION
**Pull request by celine168**
Resolves #20, based on PR https://github.com/LibreTexts/ckeditor-binder-plugin/pull/21

### CODE REVIEW

**Comment by moorepants** [comment]
Can you show a screenshot of the new buttons?

**Review by narrator0 — CHANGES_REQUESTED** [review]
The code in `onOk()` looks nice. But we still need to retrieve the values in `onShow()`. There are some code there that also needs to be changed.

**Comment by celine168** [comment]
Good catch!
Here's a screenshot:
image

**Review by narrator0 — APPROVED** [review]
LGTM!

**Pull request merged**
