### PR TITLE
Release 1.8.0

### PR DESCRIPTION
**Pull request by sandertyu**
This release includes the unset CSS fix to allow ipyleaflet plots to display as well as some small security dependency upgrades. I messed up the commit log, but current changes reflect what we want. This PR should be good to merge

### CODE REVIEW

**Comment by moorepants** [comment]
Just to confirm, you've run this locally and on query with the dependency updates?

**Comment by sandertyu** [comment]
Yes and I just ran again, everything works fine.

**Comment by moorepants** [comment]
Great, just make sure to report that in the PRs. Bumping dependencies can cause issues.

**Comment by mandeepika** [comment]
Tested the updates on ckeditor locally and on query. It works as expected!

**Pull request merged**
