### PR TITLE
Add disabling of checkboxes if one is checked

### LINKED ISSUE #20: Should not allow both checkboxes checked

### PR DESCRIPTION
**Pull request by celine168**
Disables either checkbox based if the other is checked. Resolves #20 

(I didn't have WiFi on my computer at the DMV so I worked on this instead.)

### CODE REVIEW

**Review by narrator0 — COMMENTED** [review]
Will it be confusing not being able to click the other checkbox without any warning? I think we could either:

* add a label `you can only check one at a time`
* or instead of disabling, just unclick the other checkbox

**Comment by celine168** [comment]
I guess another option would be to have 3 radio buttons: 1 with showing
everything, 1 with only showing code, and 1 with only showing the output.

**Comment by celine168** [comment]
@narrator0 @tkumar98 , tagging for thoughts.

**Comment by narrator0** [comment]
I think a radio button would be good.

**Comment by tannavee** [comment]
Yeah I think a radio button would be good too, but also the Hao mentioned how it can unclick the other box

**Comment by narrator0** [comment]
@celine168 Do you plan on fixing this?

**Comment by celine168** [comment]
The current PR contains disabling checkboxes if one is checked. If we want radio buttons, I can make those if that's the consensus.

**Comment by narrator0** [comment]
I think all of us think a radio button is good. You might want to just close this PR and open a new one.

**Pull request closed without merging**
