### PR TITLE
1.2.0 release

### PR DESCRIPTION
**Pull request by rkevin-arch**
As title. Tested by me and @sandertyu. A [changelog](https://github.com/LibreTexts/ckeditor-binder-plugin/blob/1.2.0-release/release/1.2.0.md) is also available. The main purpose of this version is to put #102 into effect so we can fix https://github.com/LibreTexts/metalc/issues/175. @moorepants We can discuss this during the meeting today.

### CODE REVIEW

**Comment by rkevin-arch** [comment]
BTW, ignore the commit diff by GitHub. For some reason, a bunch of commits already merged in #87 are showing up as different (GitHub registered #87 not as a merge for some reason, the [relevant commit](https://github.com/LibreTexts/ckeditor-binder-plugin/commit/d8993bb64e0ff151c64d797ab45f404d06536ecb) only has one parent rather than 2 for a normal mege), but I looked through all the commits one by one and identified the ones that are actually different in the changelog.

**Comment by moorepants** [comment]
This is working on query:
Selection_721

**Comment by moorepants** [comment]
Here are the packages now available:

```
Package Name       | Version | Installation directory
-------------------+---------+-----------------------
              bim  |   1.1.5 | /usr/share/octave/packages/bim-1.1.5
   communications  |   1.2.1 | /usr/share/octave/packages/communications-1.2.1
          control *|   3.0.0 | /usr/share/octave/packages/control-3.0.0
   data-smoothing  |   1.3.0 | /usr/share/octave/packages/data-smoothing-1.3.0
        dataframe  |   1.2.0 | /usr/share/octave/packages/dataframe-1.2.0
           divand  |   1.1.2 | /usr/share/octave/packages/divand-1.1.2
     econometrics  |   1.1.1 | /usr/share/octave/packages/econometrics-1.1.1
        financial  |   0.5.1 | /usr/share/octave/packages/financial-0.5.1
              fpl  |   1.3.5 | /usr/share/octave/packages/fpl-1.3.5
               ga  |  0.10.0 | /usr/share/octave/packages/ga-0.10.0
          general  |   2.0.0 | /usr/share/octave/packages/general-2.0.0
         geometry  |   3.0.0 | /usr/share/octave/packages/geometry-3.0.0
              gsl  |   2.1.0 | /usr/share/octave/packages/gsl-2.1.0
            image  |   2.6.2 | /usr/share/octave/packages/image-2.6.2
         interval  |   3.1.0 | /usr/share/octave/packages/interval-3.1.0
               io  |  2.4.10 | /usr/share/octave/packages/io-2.4.10
   linear-algebra  |   2.2.2 | /usr/share/octave/packages/linear-algebra-2.2.2
            ltfat  |   2.2.0 | /usr/share/octave/packages/ltfat-2.2.0
          mapping  |   1.2.1 | /usr/share/octave/packages/mapping-1.2.1
    miscellaneous  |   1.2.1 | /usr/share/octave/packages/miscellaneous-1.2.1
missing-functions  |   1.0.2 | .../share/octave/packages/missing-functions-1.0.2
              mpi  |   1.2.0 | /usr/share/octave/packages/mpi-1.2.0
              msh  |  1.0.10 | /usr/share/octave/packages/msh-1.0.10
              nan  |   3.1.4 | /usr/share/octave/packages/nan-3.1.4
           netcdf  |  1.0.11 | /usr/share/octave/packages/netcdf-1.0.11
            nurbs  |  1.3.13 | /usr/share/octave/packages/nurbs-1.3.13
              ocs  |   0.1.5 | /usr/share/octave/packages/ocs-0.1.5
          octclip  |   1.0.8 | /usr/share/octave/packages/octclip-1.0.8
          octproj  |   1.1.5 | /usr/share/octave/packages/octproj-1.1.5
           odepkg  |   0.8.5 | /usr/share/octave/packages/odepkg-0.8.5
            optim  |   1.5.2 | /usr/share/octave/packages/optim-1.5.2
      optiminterp  |   0.3.4 | /usr/share/octave/packages/optiminterp-0.3.4
         parallel  |   3.1.1 | /usr/share/octave/packages/parallel-3.1.1
       quaternion  |   2.4.0 | /usr/share/octave/packages/quaternion-2.4.0
           secs1d  |   0.0.9 | /usr/share/octave/packages/secs1d-0.0.9
           secs2d  |   0.0.8 | /usr/share/octave/packages/secs2d-0.0.8
           signal  |   1.3.2 | /usr/share/octave/packages/signal-1.3.2
          sockets  |   1.2.0 | /usr/share/octave/packages/sockets-1.2.0
        sparsersb  |   1.0.5 | /usr/share/octave/packages/sparsersb-1.0.5
          specfun  |   1.1.0 | /usr/share/octave/packages/specfun-1.1.0
          splines  |   1.3.2 | /usr/share/octave/packages/splines-1.3.2
       statistics  |   1.3.0 | /usr/share/octave/packages/statistics-1.3.0
              stk  |   2.5.0 | /usr/share/octave/packages/stk-2.5.0
          strings  |   1.2.0 | /usr/share/octave/packages/strings-1.2.0
           struct  |  1.0.14 | /usr/share/octave/packages/struct-1.0.14
         symbolic  |   2.6.0 | /usr/share/octave/packages/symbolic-2.6.0
           tisean  |   0.2.3 | /usr/share/octave/packages/tisean-0.2.3
              tsa  |   4.4.5 | /usr/share/octave/packages/tsa-4.4.5
             vrml  |  1.0.13 | /usr/share/octave/packages/vrml-1.0.13
           zenity  |   0.5.7 | /usr/share/octave/packages/zenity-0.5.7
           zeromq  |   1.2.1 | /usr/share/octave/packages/zeromq-1.2.1
```

**Review by moorepants — APPROVED** [review]

**Comment by moorepants** [comment]
Tested on query.

**Pull request merged**
